# Generated by Django 4.2.3 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0015_alter_logentry_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='service_actor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Service Actor'),
        ),
    ]
